version: '3.7'
services:
  api:
    image: api:latest
    ports:
      - 8080:8080
    networks:
      - webproxy

  test:
    image: test:latest
    depends_on:
      - api
    ports:
      - 8081:8080
    networks:
      - webproxy

networks:
  webproxy:
    driver: bridge