name: Build

on:
  push:
    branches:
      - master

jobs:
  prepare:
    name: Build with j13
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo fagkveld-feb-2020
        uses: actions/checkout@master
      - name: Setup Java 13/Maven
        uses: actions/setup-java@v1
        with:
          java-version: 13
      - name: build
        run: mvn clean compile
      - name: Containerize
        run: docker build -t no/tordly/fagkveld .
      - name: Run
      - run: docker run -p 8080:8080 -t no/tordly/fagkveld