name: Build And Find Security flaws

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Containerize
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@master
      - name: Cache Maven Dependencies
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Setup Java 13/Maven
        uses: actions/setup-java@v1
        with:
          java-version: 13
      - name: Build with JDK 13
        run: mvn clean package -T C1 -DskipTests
      - name: Containerize with Docker
        run: |
          docker build -f .docker/Dockerfile -t no/tordly/fagkveld .
      - name: Publish Container [Github Package Registry]
        run: |
          docker login docker.pgk.github.com -u $GITHUB_REPOSITORY -p ${{ secrets.GITHUB_TOKEN }}
          docker push no/tordly/fagkveld

  snyk:
    name: Snyk Monitor
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: actions/setup-java@v1
        with:
          java-version: 13
      - run: mvn snyk:monitor -Dsnyk-api-token=${{ secrets.SNYK_TOKEN }}