name: Test PR

on: pull_request

jobs:
  build:
    name: Build and Containerize
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@master
      - name: Cache Maven Dependencies
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Setup Java 13/Maven
        uses: actions/setup-java@v1
        with:
          java-version: 13
      - name: Build and Test [JDK 13]
        run: mvn clean package -T C1
      - name: Containerize [Docker]
        run: |
          docker build -f .docker/api.Dockerfile -t api .
          docker build -f .docker/test.Dockerfile -t test .
          docker-compose -f .docker/docker-compose.yml up --exit-code-from test
  snyk:
    name: Snyk Monitor
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: actions/setup-java@v1
        with:
          java-version: 13
      - run: mvn snyk:monitor -Dsnyk-api-token=${{ secrets.SNYK_TOKEN }}